name: CI Pipeline

on:
  push:
    branches:
      - main  # Se ejecutará en cada push a la rama 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # Utiliza una máquina con Ubuntu para ejecutar el workflow

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Clona tu repositorio

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Configura la versión de Node.js

      - name: Install dependencies
        run: npm install  # Instala las dependencias del proyecto React

      - name: Build React app
        run: npm run build --loglevel verbose  # Ejecuta el build de app React con logs detallados

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  # Configura Docker Buildx para el build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Usa tu nombre de usuario de Docker Hub como secreto
          password: ${{ secrets.DOCKER_PASSWORD }}  # Usa tu contraseña de Docker Hub como secreto

      - name: Verificar contenido del build
        run: ls -R dist  # Comprueba que se generó correctamente la carpeta 'dist'

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest ${{ secrets.DOCKER_USERNAME }}/my-react-app:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-react-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-react-app:${{ github.sha }}
